export const CURRICULUM = [
  {
    id: 'cs-mod-1',
    title: 'C# basico',
    description: 'Sintaxis .NET y programacion orientada a objetos',
    lessons: [
      {
        id: 'cs-l01',
        title: '1. Hola mundo',
        duration: '10 min',
        theory: `<p><strong>C#</strong> usa <code>Console.WriteLine()</code> para imprimir. Cada instruccion termina en <code>;</code>.</p>`,
        example: { code: `Console.WriteLine("Hola, C#");`, explanation: 'WriteLine agrega salto de linea.' },
        exercise: {
          instructions: 'Imprime: Aprendo C#',
          starterCode: `// Tu codigo\n`,
          hint: 'Console.WriteLine("Aprendo C#");',
          solution: `Console.WriteLine("Aprendo C#");`,
          runner: 'csharp',
          tests: `
            if (__logs.length === 0) throw new Error('Usa Console.WriteLine');
            if (__logs[0] !== 'Aprendo C#') throw new Error('Salida incorrecta');
          `,
        },
      },
      {
        id: 'cs-l02',
        title: '2. Variables y tipos',
        duration: '12 min',
        theory: `<p><code>int</code>, <code>string</code>, <code>double</code>, <code>bool</code>. Declara con tipo explicito.</p>`,
        example: { code: `int edad = 25;\nstring nombre = "Ana";\nConsole.WriteLine(nombre);`, explanation: 'Tipado estatico.' },
        exercise: {
          instructions: 'int puntos = 100; imprime puntos.',
          starterCode: ``,
          hint: 'Console.WriteLine(puntos);',
          solution: `int puntos = 100;\nConsole.WriteLine(puntos);`,
          runner: 'csharp',
          tests: `if (__logs[0] !== '100') throw new Error('Imprime 100');`,
        },
      },
      {
        id: 'cs-l03',
        title: '3. if / else',
        duration: '12 min',
        theory: `<p>Condicionales con llaves <code>{ }</code>. Comparaciones: ==, !=, &gt;, &lt;.</p>`,
        example: { code: `int x = 10;\nif (x > 5) {\n  Console.WriteLine("Grande");\n}`, explanation: 'Condicion entre parentesis.' },
        exercise: {
          instructions: 'bool activo = true; si activo imprime "Si", sino "No".',
          starterCode: ``,
          hint: 'if (activo) {',
          solution: `bool activo = true;\nif (activo) {\n  Console.WriteLine("Si");\n} else {\n  Console.WriteLine("No");\n}`,
          runner: 'csharp',
          tests: `if (__logs[0] !== 'Si') throw new Error('Debe imprimir Si');`,
        },
      },
      {
        id: 'cs-l04',
        title: '4. Bucles for',
        duration: '12 min',
        theory: `<p><code>for (int i = 0; i &lt; n; i++)</code> es el bucle clasico en C#.</p>`,
        example: { code: `for (int i = 0; i < 3; i++) {\n  Console.WriteLine(i);\n}`, explanation: 'i++ incrementa.' },
        exercise: {
          instructions: 'Imprime 1, 2, 3 con un for (empieza en i=1, i<=3).',
          starterCode: ``,
          hint: 'for (int i = 1; i <= 3; i++)',
          solution: `for (int i = 1; i <= 3; i++) {\n  Console.WriteLine(i);\n}`,
          runner: 'csharp',
          tests: `if (__logs.join(',') !== '1,2,3') throw new Error('Imprime 1,2,3');`,
        },
      },
      {
        id: 'cs-l05',
        title: '5. Metodos',
        duration: '14 min',
        theory: `<p><code>static tipo Nombre(params) { return ...; }</code> define metodos.</p>`,
        example: { code: `static int Suma(int a, int b) {\n  return a + b;\n}\nConsole.WriteLine(Suma(2, 3));`, explanation: 'return devuelve valor.' },
        exercise: {
          instructions: 'Metodo static int Triple(int n) retorna n*3. Imprime Triple(4).',
          starterCode: ``,
          hint: 'static int Triple(int n) { return n * 3; }',
          solution: `static int Triple(int n) {\n  return n * 3;\n}\nConsole.WriteLine(Triple(4));`,
          runner: 'csharp',
          tests: `if (__logs[0] !== '12') throw new Error('Triple(4)=12');`,
        },
      },
      {
        id: 'cs-l06',
        title: '6. Clases',
        duration: '16 min',
        theory: `<p><code>class Persona { public string Nombre; }</code> — POO en C#.</p>`,
        example: { code: `class Persona {\n  public string Nombre;\n}\nvar p = new Persona();\np.Nombre = "Luis";\nConsole.WriteLine(p.Nombre);`, explanation: 'new crea instancia.' },
        exercise: {
          instructions: 'Clase Producto con public string Nombre. Crea instancia, Nombre="Teclado", imprimelo.',
          starterCode: ``,
          hint: 'class Producto { public string Nombre; }',
          solution: `class Producto {\n  public string Nombre;\n}\nvar p = new Producto();\np.Nombre = "Teclado";\nConsole.WriteLine(p.Nombre);`,
          runner: 'csharp',
          tests: `if (__logs[0] !== 'Teclado') throw new Error('Imprime Teclado');`,
        },
      },
    ],
  },
  {
    id: 'cs-mod-2',
    title: 'C# intermedio',
    description: 'Strings, tipos y mas POO',
    lessons: [
      {
        id: 'cs-l07',
        title: '7. Tipo double',
        duration: '12 min',
        theory: `<p><code>double</code> almacena decimales: <code>double pi = 3.14;</code></p>`,
        example: { code: `double precio = 9.99;\nConsole.WriteLine(precio);`, explanation: 'Usa punto decimal.' },
        exercise: {
          instructions: 'double nota = 8.5; imprime nota.',
          starterCode: ``,
          hint: 'double nota = 8.5;',
          solution: `double nota = 8.5;\nConsole.WriteLine(nota);`,
          runner: 'csharp',
          tests: `if (__logs[0] !== '8.5') throw new Error('Imprime 8.5');`,
        },
      },
      {
        id: 'cs-l08',
        title: '8. Concatenar strings',
        duration: '12 min',
        theory: `<p>Usa <code>+</code> para unir textos: <code>"Hola " + nombre</code></p>`,
        example: { code: `string a = "Hola";\nstring b = "Mundo";\nConsole.WriteLine(a + " " + b);`, explanation: 'Concatenacion basica.' },
        exercise: {
          instructions: 'string saludo = "Bienvenido"; string user = "Ana"; imprime saludo + " " + user',
          starterCode: ``,
          hint: 'Console.WriteLine(saludo + " " + user);',
          solution: `string saludo = "Bienvenido";\nstring user = "Ana";\nConsole.WriteLine(saludo + " " + user);`,
          runner: 'csharp',
          tests: `if (__logs[0] !== 'Bienvenido Ana') throw new Error('Bienvenido Ana');`,
        },
      },
      {
        id: 'cs-l09',
        title: '9. Metodo Resta',
        duration: '12 min',
        theory: `<p>Metodos pueden recibir multiples parametros y retornar cualquier tipo.</p>`,
        example: { code: `static int Resta(int a, int b) {\n  return a - b;\n}\nConsole.WriteLine(Resta(10, 3));`, explanation: 'return devuelve el resultado.' },
        exercise: {
          instructions: 'static int Multiplica(int a, int b) retorna a*b. Imprime Multiplica(6, 7).',
          starterCode: ``,
          hint: 'return a * b;',
          solution: `static int Multiplica(int a, int b) {\n  return a * b;\n}\nConsole.WriteLine(Multiplica(6, 7));`,
          runner: 'csharp',
          tests: `if (__logs[0] !== '42') throw new Error('Multiplica(6,7)=42');`,
        },
      },
      {
        id: 'cs-l10',
        title: '10. Clase con int',
        duration: '14 min',
        theory: `<p>Las propiedades pueden ser de cualquier tipo: <code>public int Edad;</code></p>`,
        example: { code: `class Persona {\n  public int Edad;\n}\nvar p = new Persona();\np.Edad = 30;\nConsole.WriteLine(p.Edad);`, explanation: 'Accede con punto.' },
        exercise: {
          instructions: 'Clase Coche con public int Anio = 2020. Crea instancia e imprime Anio.',
          starterCode: ``,
          hint: 'class Coche { public int Anio; }',
          solution: `class Coche {\n  public int Anio;\n}\nvar c = new Coche();\nc.Anio = 2020;\nConsole.WriteLine(c.Anio);`,
          runner: 'csharp',
          tests: `if (__logs[0] !== '2020') throw new Error('Imprime 2020');`,
        },
      },
      {
        id: 'cs-l11',
        title: '11. Bucles anidados',
        duration: '14 min',
        theory: `<p>Puedes contar del 1 al 5 con for e imprimir cada numero.</p>`,
        example: { code: `for (int i = 1; i <= 3; i++) {\n  Console.WriteLine(i);\n}`, explanation: 'Un numero por linea.' },
        exercise: {
          instructions: 'Imprime 1, 2, 3, 4, 5 con for (i=1; i<=5; i++).',
          starterCode: ``,
          hint: 'for (int i = 1; i <= 5; i++)',
          solution: `for (int i = 1; i <= 5; i++) {\n  Console.WriteLine(i);\n}`,
          runner: 'csharp',
          tests: `if (__logs.join(',') !== '1,2,3,4,5') throw new Error('Imprime 1 a 5');`,
        },
      },
      {
        id: 'cs-l12',
        title: '12. Metodo auxiliar',
        duration: '14 min',
        theory: `<p>Metodos que retornan valor se usan dentro de <code>Console.WriteLine</code>.</p>`,
        example: { code: `static string Saludar(string n) {\n  return "Hola " + n;\n}\nConsole.WriteLine(Saludar("Luis"));`, explanation: 'Retorna string para imprimir.' },
        exercise: {
          instructions: 'static string Eco(string msg) retorna msg. Imprime Eco("OK").',
          starterCode: ``,
          hint: 'return msg;',
          solution: `static string Eco(string msg) {\n  return msg;\n}\nConsole.WriteLine(Eco("OK"));`,
          runner: 'csharp',
          tests: `if (__logs[0] !== 'OK') throw new Error('Imprime OK');`,
        },
      },
    ],
  },
  {
    id: 'cs-mod-3',
    title: 'C# practico',
    description: 'Logica, condiciones y proyecto final',
    lessons: [
      {
        id: 'cs-l13',
        title: '13. Comparaciones',
        duration: '12 min',
        theory: `<p>Operadores: <code>==</code>, <code>!=</code>, <code>&gt;</code>, <code>&lt;</code>, <code>&gt;=</code></p>`,
        example: { code: `int a = 10;\nif (a >= 10) {\n  Console.WriteLine("Mayor o igual");\n}`, explanation: 'Condiciones numericas.' },
        exercise: {
          instructions: 'int x = 5; if (x > 3) imprime "Si", else "No".',
          starterCode: ``,
          hint: 'if (x > 3) { Console.WriteLine("Si");',
          solution: `int x = 5;\nif (x > 3) {\n  Console.WriteLine("Si");\n} else {\n  Console.WriteLine("No");\n}`,
          runner: 'csharp',
          tests: `if (__logs[0] !== 'Si') throw new Error('Debe imprimir Si');`,
        },
      },
      {
        id: 'cs-l14',
        title: '14. Metodo con string',
        duration: '12 min',
        theory: `<p>Metodos pueden retornar <code>string</code> para formatear texto.</p>`,
        example: { code: `static string Etiqueta(string n) {\n  return "User: " + n;\n}\nConsole.WriteLine(Etiqueta("Ana"));`, explanation: 'Combina texto y variables.' },
        exercise: {
          instructions: 'static string Mayus(string s) retorna s + "!". Imprime Mayus("Hola").',
          starterCode: ``,
          hint: 'return s + "!";',
          solution: `static string Mayus(string s) {\n  return s + "!";\n}\nConsole.WriteLine(Mayus("Hola"));`,
          runner: 'csharp',
          tests: `if (__logs[0] !== 'Hola!') throw new Error('Hola!');`,
        },
      },
      {
        id: 'cs-l15',
        title: '15. Dos clases',
        duration: '14 min',
        theory: `<p>Puedes definir varias clases en el mismo archivo.</p>`,
        example: { code: `class A { public string Nombre; }\nclass B { public int Valor; }`, explanation: 'Organiza tu codigo.' },
        exercise: {
          instructions: 'Clase Libro { public string Titulo; }. Crea libro, Titulo="1984", imprimelo.',
          starterCode: ``,
          hint: 'var libro = new Libro();',
          solution: `class Libro {\n  public string Titulo;\n}\nvar libro = new Libro();\nlibro.Titulo = "1984";\nConsole.WriteLine(libro.Titulo);`,
          runner: 'csharp',
          tests: `if (__logs[0] !== '1984') throw new Error('Imprime 1984');`,
        },
      },
      {
        id: 'cs-l16',
        title: '16. bool en condiciones',
        duration: '12 min',
        theory: `<p><code>bool</code> almacena true/false. Ideal para flags y estados.</p>`,
        example: { code: `bool activo = false;\nif (activo) {\n  Console.WriteLine("On");\n} else {\n  Console.WriteLine("Off");\n}`, explanation: 'false va al else.' },
        exercise: {
          instructions: 'bool premium = false; if premium imprime "Pro" else "Free".',
          starterCode: ``,
          hint: 'if (premium) { Console.WriteLine("Pro");',
          solution: `bool premium = false;\nif (premium) {\n  Console.WriteLine("Pro");\n} else {\n  Console.WriteLine("Free");\n}`,
          runner: 'csharp',
          tests: `if (__logs[0] !== 'Free') throw new Error('Imprime Free');`,
        },
      },
      {
        id: 'cs-l17',
        title: '17. Tabla de multiplicar',
        duration: '16 min',
        theory: `<p>Combina for con operaciones aritmeticas para generar patrones.</p>`,
        example: { code: `for (int i = 1; i <= 3; i++) {\n  Console.WriteLine(i * 2);\n}`, explanation: 'Imprime 2, 4, 6.' },
        exercise: {
          instructions: 'Imprime 3, 6, 9 con for (i=1; i<=3; i++) imprimiendo i*3.',
          starterCode: ``,
          hint: 'Console.WriteLine(i * 3);',
          solution: `for (int i = 1; i <= 3; i++) {\n  Console.WriteLine(i * 3);\n}`,
          runner: 'csharp',
          tests: `if (__logs.join(',') !== '3,6,9') throw new Error('Imprime 3,6,9');`,
        },
      },
      {
        id: 'cs-l18',
        title: '18. Proyecto: Estudiante',
        duration: '20 min',
        theory: `<p>Combina clase, propiedades y metodo estatico para un mini modelo de datos.</p>`,
        example: { code: `class Alumno {\n  public string Nombre;\n  public int Nota;\n}\nvar a = new Alumno();\na.Nombre = "Luis";\na.Nota = 9;\nConsole.WriteLine(a.Nombre);`, explanation: 'Modelo simple de entidad.' },
        exercise: {
          instructions: 'Clase Estudiante { public string Nombre; public int Edad; }. Crea uno: Nombre="Sara", Edad=22. Imprime Nombre y Edad en lineas separadas.',
          starterCode: ``,
          hint: 'Console.WriteLine(e.Nombre); luego Edad',
          solution: `class Estudiante {\n  public string Nombre;\n  public int Edad;\n}\nvar e = new Estudiante();\ne.Nombre = "Sara";\ne.Edad = 22;\nConsole.WriteLine(e.Nombre);\nConsole.WriteLine(e.Edad);`,
          runner: 'csharp',
          tests: `
            if (__logs[0] !== 'Sara') throw new Error('Primera linea Sara');
            if (__logs[1] !== '22') throw new Error('Segunda linea 22');
          `,
        },
      },
    ],
  },
];
