export const CURRICULUM = [
  {
    id: 'py-mod-1',
    title: 'Python esencial',
    description: 'Sintaxis, logica y estructuras basicas',
    lessons: [
      {
        id: 'py-l01',
        title: '1. print y hola mundo',
        duration: '8 min',
        theory: `<p><strong>Python</strong> usa <code>print()</code> para mostrar texto.</p>`,
        example: { code: `print("Hola, Python")\nprint(42)`, explanation: 'print muestra en consola.' },
        exercise: {
          instructions: 'Imprime exactamente: Aprendo Python',
          starterCode: `# Escribe aqui\n`,
          hint: 'print("Aprendo Python")',
          solution: `print("Aprendo Python")`,
          runner: 'python',
          tests: `
            if (__logs.length === 0) throw new Error('Usa print()');
            if (__logs[0] !== 'Aprendo Python') throw new Error('Salida incorrecta');
          `,
        },
      },
      {
        id: 'py-l02',
        title: '2. Variables',
        duration: '10 min',
        theory: `<p>Asigna con <code>=</code>. Tipos: str, int, float, bool.</p>`,
        example: { code: `nombre = "Ana"\nedad = 25\nprint(nombre, edad)`, explanation: 'Sin declarar tipo.' },
        exercise: {
          instructions: 'ciudad="Madrid", temp=22, imprime "Madrid: 22"',
          starterCode: ``,
          hint: 'print(ciudad + ": " + str(temp))',
          solution: `ciudad = "Madrid"\ntemp = 22\nprint(ciudad + ": " + str(temp))`,
          runner: 'python',
          tests: `if (__logs[0] !== 'Madrid: 22') throw new Error('Salida: Madrid: 22');`,
        },
      },
      {
        id: 'py-l03',
        title: '3. if / else',
        duration: '12 min',
        theory: `<p>Condicionales con indentacion: <code>if</code>, <code>elif</code>, <code>else</code>.</p>`,
        example: { code: `nota = 85\nif nota >= 60:\n    print("Aprobado")\nelse:\n    print("Suspenso")`, explanation: 'Dos puntos y sangria.' },
        exercise: {
          instructions: 'edad=20, si edad>=18 imprime "Mayor", sino "Menor".',
          starterCode: `edad = 20\n`,
          hint: 'if edad >= 18:',
          solution: `edad = 20\nif edad >= 18:\n    print("Mayor")\nelse:\n    print("Menor")`,
          runner: 'python',
          tests: `if (__logs[0] !== 'Mayor') throw new Error('Debe imprimir Mayor');`,
        },
      },
      {
        id: 'py-l04',
        title: '4. Bucles for',
        duration: '12 min',
        theory: `<p><code>for i in range(n):</code> y <code>for item in lista:</code>.</p>`,
        example: { code: `for i in range(3):\n    print(i)`, explanation: 'range(3) -> 0,1,2' },
        exercise: {
          instructions: 'Imprime 1, 2, 3 en lineas separadas con for y range.',
          starterCode: ``,
          hint: 'for i in range(1, 4):',
          solution: `for i in range(1, 4):\n    print(i)`,
          runner: 'python',
          tests: `if (__logs.join(',') !== '1,2,3') throw new Error('Imprime 1, 2, 3');`,
        },
      },
      {
        id: 'py-l05',
        title: '5. Funciones',
        duration: '14 min',
        theory: `<p><code>def nombre():</code> y <code>return</code>.</p>`,
        example: { code: `def saludar(n):\n    return "Hola " + n\nprint(saludar("Luis"))`, explanation: 'Parametros opcionales.' },
        exercise: {
          instructions: 'Funcion doble(x) retorna x*2. Imprime doble(5).',
          starterCode: ``,
          hint: 'def doble(x):\n    return x * 2',
          solution: `def doble(x):\n    return x * 2\nprint(doble(5))`,
          runner: 'python',
          tests: `if (__logs[0] !== '10') throw new Error('doble(5) = 10');`,
        },
      },
      {
        id: 'py-l06',
        title: '6. Listas',
        duration: '12 min',
        theory: `<p>Listas <code>[1,2,3]</code>, append, len, indices [0].</p>`,
        example: { code: `nums = [10, 20, 30]\nprint(nums[0])\nprint(len(nums))`, explanation: 'Indices desde 0.' },
        exercise: {
          instructions: 'frutas=["manzana","pera"], imprime len(frutas).',
          starterCode: ``,
          hint: 'frutas = ["manzana", "pera"]',
          solution: `frutas = ["manzana", "pera"]\nprint(len(frutas))`,
          runner: 'python',
          tests: `if (__logs[0] !== '2') throw new Error('len = 2');`,
        },
      },
    ],
  },
  {
    id: 'py-mod-2',
    title: 'Python intermedio',
    description: 'Bucles, diccionarios, errores y proyectos',
    lessons: [
      {
        id: 'py-l07',
        title: '7. while',
        duration: '12 min',
        theory: `<p><code>while condicion:</code> repite mientras sea verdadera. Cuidado con bucles infinitos.</p>`,
        example: { code: `n = 3\nwhile n > 0:\n    print(n)\n    n -= 1`, explanation: 'Decrementa n cada vuelta.' },
        exercise: {
          instructions: 'Cuenta regresiva: imprime 3, 2, 1 con while.',
          starterCode: `n = 3\n`,
          hint: 'while n > 0:',
          solution: `n = 3\nwhile n > 0:\n    print(n)\n    n -= 1`,
          runner: 'python',
          tests: `if (__logs.join(',') !== '3,2,1') throw new Error('Imprime 3,2,1');`,
        },
      },
      {
        id: 'py-l08',
        title: '8. Diccionarios',
        duration: '14 min',
        theory: `<p><code>{"clave": valor}</code>. Acceso con <code>dict["clave"]</code> o <code>.get()</code>.</p>`,
        example: { code: `user = {"nombre": "Ana", "edad": 25}\nprint(user["nombre"])`, explanation: 'Pares clave-valor.' },
        exercise: {
          instructions: 'Dict pais={"capital":"Madrid","pais":"Espana"}, imprime pais["capital"].',
          starterCode: ``,
          hint: 'pais = {"capital": "Madrid", "pais": "Espana"}',
          solution: `pais = {"capital": "Madrid", "pais": "Espana"}\nprint(pais["capital"])`,
          runner: 'python',
          tests: `if (__logs[0] !== 'Madrid') throw new Error('Imprime Madrid');`,
        },
      },
      {
        id: 'py-l09',
        title: '9. for en diccionarios',
        duration: '12 min',
        theory: `<p><code>for k in dict:</code>, <code>.keys()</code>, <code>.values()</code>, <code>.items()</code>.</p>`,
        example: { code: `precios = {"pan": 1, "leche": 2}\nfor p in precios:\n    print(p, precios[p])`, explanation: 'Itera claves.' },
        exercise: {
          instructions: 'notas={"math":10,"code":9}, imprime cada clave y valor en lineas "math:10" y "code:9".',
          starterCode: `notas = {"math": 10, "code": 9}\n`,
          hint: 'for k in notas:\n    print(k + ":" + str(notas[k]))',
          solution: `notas = {"math": 10, "code": 9}\nfor k in notas:\n    print(str(k) + ":" + str(notas[k]))`,
          runner: 'python',
          tests: `
            if (!__logs.includes('math:10') || !__logs.includes('code:9')) throw new Error('Lineas math:10 y code:9');
          `,
        },
      },
      {
        id: 'py-l10',
        title: '10. try / except',
        duration: '14 min',
        theory: `<p>Captura errores sin detener el programa: <code>try:</code> ... <code>except:</code>.</p>`,
        example: { code: `try:\n    x = int("abc")\nexcept:\n    print("Error")`, explanation: 'Evita crashes.' },
        exercise: {
          instructions: 'try convertir "42" a int e imprimirlo; except imprime "Fallo". (Debe imprimir 42)',
          starterCode: ``,
          hint: 'try:\n    print(int("42"))',
          solution: `try:\n    print(int("42"))\nexcept:\n    print("Fallo")`,
          runner: 'python',
          tests: `if (__logs[0] !== '42') throw new Error('Imprime 42');`,
        },
      },
      {
        id: 'py-l11',
        title: '11. List comprehensions',
        duration: '14 min',
        theory: `<p>Crea listas en una linea: <code>[x*2 for x in range(5)]</code>.</p>`,
        example: { code: `cuadrados = [n**2 for n in range(4)]\nprint(cuadrados)`, explanation: 'Compacto y legible.' },
        exercise: {
          instructions: 'Crea pares=[n*2 for n in range(1,4)] e imprime pares (debe ser [2,4,6]).',
          starterCode: ``,
          hint: 'pares = [n*2 for n in range(1, 4)]',
          solution: `pares = [n*2 for n in range(1, 4)]\nprint(pares)`,
          runner: 'python',
          tests: `if (__logs[0] !== '[2, 4, 6]') throw new Error('Imprime [2, 4, 6]');`,
        },
      },
      {
        id: 'py-l12',
        title: '12. Parametros por defecto',
        duration: '12 min',
        theory: `<p><code>def saludar(nombre="mundo"):</code> — parametros opcionales.</p>`,
        example: { code: `def greet(name="mundo"):\n    print("Hola " + name)\ngreet()\ngreet("Ana")`, explanation: 'Default si no pasas argumento.' },
        exercise: {
          instructions: 'def potencia(base, exp=2) retorna base**exp. Imprime potencia(3) y potencia(2,3).',
          starterCode: ``,
          hint: 'def potencia(base, exp=2):',
          solution: `def potencia(base, exp=2):\n    return base ** exp\nprint(potencia(3))\nprint(potencia(2, 3))`,
          runner: 'python',
          tests: `
            if (__logs[0] !== '9') throw new Error('potencia(3)=9');
            if (__logs[1] !== '8') throw new Error('potencia(2,3)=8');
          `,
        },
      },
      {
        id: 'py-l13',
        title: '13. Proyecto: FizzBuzz',
        duration: '18 min',
        theory: `<p>Clasico ejercicio: imprime numeros 1-15, pero "Fizz" si multiplo de 3, "Buzz" si de 5, "FizzBuzz" si ambos.</p>`,
        example: { code: `for i in range(1, 6):\n    if i % 15 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)`, explanation: 'Combina if y for.' },
        exercise: {
          instructions: 'Imprime FizzBuzz solo para i=15 (una linea "FizzBuzz").',
          starterCode: `i = 15\n`,
          hint: 'if i % 15 == 0: print("FizzBuzz")',
          solution: `i = 15\nif i % 15 == 0:\n    print("FizzBuzz")`,
          runner: 'python',
          tests: `if (__logs[0] !== 'FizzBuzz') throw new Error('Imprime FizzBuzz');`,
        },
      },
    ],
  },
  {
    id: 'py-mod-3',
    title: 'Python avanzado',
    description: 'Archivos, clases y modulos',
    lessons: [
      {
        id: 'py-l14',
        title: '14. Clases',
        duration: '16 min',
        theory: `<p><code>class Persona:</code> con <code>__init__</code> constructor y metodos.</p>`,
        example: { code: `class Perro:\n    def __init__(self, nombre):\n        self.nombre = nombre\n    def ladrar(self):\n        return self.nombre + " guau"\np = Perro("Max")\nprint(p.ladrar())`, explanation: 'self es la instancia.' },
        exercise: {
          instructions: 'class Cuadrado con __init__(self, lado) y metodo area() retorna lado*lado. c=Cuadrado(4), print(c.area()).',
          starterCode: ``,
          hint: 'def area(self): return self.lado * self.lado',
          solution: `class Cuadrado:\n    def __init__(self, lado):\n        self.lado = lado\n    def area(self):\n        return self.lado * self.lado\nc = Cuadrado(4)\nprint(c.area())`,
          runner: 'python',
          tests: `if (__logs[0] !== '16') throw new Error('area=16');`,
        },
      },
      {
        id: 'py-l15',
        title: '15. Herencia',
        duration: '14 min',
        theory: `<p><code>class Empleado(Persona):</code> hereda metodos y atributos de la clase padre.</p>`,
        example: { code: `class Animal:\n    def hablar(self):\n        return "..."\nclass Gato(Animal):\n    def hablar(self):\n        return "miau"\nprint(Gato().hablar())`, explanation: 'Override de metodos.' },
        exercise: {
          instructions: 'class A con metodo hi() return "A". class B(A) override hi() return "B". print(B().hi())',
          starterCode: ``,
          hint: 'class B(A): def hi(self): return "B"',
          solution: `class A:\n    def hi(self):\n        return "A"\nclass B(A):\n    def hi(self):\n        return "B"\nprint(B().hi())`,
          runner: 'python',
          tests: `if (__logs[0] !== 'B') throw new Error('Imprime B');`,
        },
      },
      {
        id: 'py-l16',
        title: '16. Modulos import',
        duration: '12 min',
        theory: `<p><code>import math</code> y <code>from math import sqrt</code> reutilizan codigo externo.</p>`,
        example: { code: `import math\nprint(math.sqrt(16))`, explanation: 'Biblioteca estandar incluida.' },
        exercise: {
          instructions: 'import math; print(math.pi redondeado no — imprime int(math.floor(9.9)))',
          starterCode: ``,
          hint: 'import math\nprint(int(math.floor(9.9)))',
          solution: `import math\nprint(int(math.floor(9.9)))`,
          runner: 'python',
          tests: `if (__logs[0] !== '9') throw new Error('floor 9.9 = 9');`,
        },
      },
      {
        id: 'py-l17',
        title: '17. Lambda',
        duration: '12 min',
        theory: `<p>Funciones anonimas: <code>lambda x: x * 2</code></p>`,
        example: { code: `doble = lambda x: x * 2\nprint(doble(5))`, explanation: 'Utiles con map/filter.' },
        exercise: {
          instructions: 'cuadrado = lambda x: x**2; print(cuadrado(6))',
          starterCode: ``,
          hint: 'lambda x: x**2',
          solution: `cuadrado = lambda x: x ** 2\nprint(cuadrado(6))`,
          runner: 'python',
          tests: `if (__logs[0] !== '36') throw new Error('6^2=36');`,
        },
      },
      {
        id: 'py-l18',
        title: '18. map y filter',
        duration: '14 min',
        theory: `<p><code>map(fn, lista)</code> transforma. <code>filter(fn, lista)</code> filtra.</p>`,
        example: { code: `nums = [1, 2, 3]\nprint(list(map(lambda x: x*2, nums)))`, explanation: 'Programacion funcional.' },
        exercise: {
          instructions: 'print(list(filter(lambda x: x > 2, [1,2,3,4])))',
          starterCode: ``,
          hint: 'filter(lambda x: x > 2, ...)',
          solution: `print(list(filter(lambda x: x > 2, [1, 2, 3, 4])))`,
          runner: 'python',
          tests: `if (__logs[0] !== '[3, 4]') throw new Error('[3, 4]');`,
        },
      },
      {
        id: 'py-l19',
        title: '19. Sets y tuplas',
        duration: '12 min',
        theory: `<p><code>set</code> sin duplicados. <code>tuple</code> inmutable con parentesis.</p>`,
        example: { code: `colores = {"rojo", "azul", "rojo"}\nprint(len(colores))`, explanation: 'Set tiene 2 elementos.' },
        exercise: {
          instructions: 't = (10, 20); print(t[1])',
          starterCode: ``,
          hint: 't = (10, 20)',
          solution: `t = (10, 20)\nprint(t[1])`,
          runner: 'python',
          tests: `if (__logs[0] !== '20') throw new Error('Imprime 20');`,
        },
      },
      {
        id: 'py-l20',
        title: '20. Proyecto: agenda',
        duration: '22 min',
        theory: `<p>Combina listas, dicts y funciones para una mini agenda de contactos.</p>`,
        example: { code: `agenda = []\ndef agregar(nombre, tel):\n    agenda.append({"nombre": nombre, "tel": tel})\nagregar("Ana", "123")\nprint(len(agenda))`, explanation: 'Lista de diccionarios.' },
        exercise: {
          instructions: 'agenda=[], funcion agregar(n) hace agenda.append(n), llama agregar("Luis") y print(len(agenda)).',
          starterCode: ``,
          hint: 'def agregar(n): agenda.append(n)',
          solution: `agenda = []\ndef agregar(n):\n    agenda.append(n)\nagregar("Luis")\nprint(len(agenda))`,
          runner: 'python',
          tests: `if (__logs[0] !== '1') throw new Error('1 contacto');`,
        },
      },
    ],
  },
];
