export const CURRICULUM = [
  {
    id: 'ts-mod-1',
    title: 'TypeScript',
    description: 'Tipos estaticos sobre JavaScript',
    lessons: [
      {
        id: 'ts-l01',
        title: '1. Tipos basicos',
        duration: '10 min',
        theory: `<p>TypeScript anade tipos a JS: <code>let x: number = 5;</code></p>`,
        example: { code: `let nombre: string = "Ana";\nlet edad: number = 25;\nconsole.log(nombre, edad);`, explanation: 'Tipos en declaracion.' },
        exercise: {
          instructions: 'let lenguaje: string = "TypeScript"; console.log(lenguaje);',
          starterCode: ``,
          hint: 'let lenguaje: string = "TypeScript";',
          solution: `let lenguaje: string = "TypeScript";\nconsole.log(lenguaje);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== 'TypeScript') throw new Error('Imprime TypeScript');`,
        },
      },
      {
        id: 'ts-l02',
        title: '2. Interfaces',
        duration: '12 min',
        theory: `<p><code>interface Usuario { nombre: string; edad: number; }</code> define forma de objetos.</p>`,
        example: { code: `interface Punto { x: number; y: number; }\nconst p: Punto = { x: 1, y: 2 };`, explanation: 'Interfaces no existen en runtime.' },
        exercise: {
          instructions: 'Interface Libro { titulo: string; }. const b: Libro = { titulo: "1984" }; console.log(b.titulo);',
          starterCode: ``,
          hint: 'interface Libro { titulo: string; }',
          solution: `interface Libro { titulo: string; }\nconst b: Libro = { titulo: "1984" };\nconsole.log(b.titulo);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== '1984') throw new Error('Imprime 1984');`,
        },
      },
      {
        id: 'ts-l03',
        title: '3. Funciones tipadas',
        duration: '12 min',
        theory: `<p><code>function suma(a: number, b: number): number</code></p>`,
        example: { code: `function doble(n: number): number {\n  return n * 2;\n}\nconsole.log(doble(5));`, explanation: 'Parametros y retorno tipados.' },
        exercise: {
          instructions: 'Funcion saludar(n: string): string retorna "Hola " + n. Imprime saludar("Mundo").',
          starterCode: ``,
          hint: 'function saludar(n: string): string',
          solution: `function saludar(n: string): string {\n  return "Hola " + n;\n}\nconsole.log(saludar("Mundo"));`,
          runner: 'typescript',
          tests: `if (__logs[0] !== 'Hola Mundo') throw new Error('Hola Mundo');`,
        },
      },
      {
        id: 'ts-l04',
        title: '4. Union types',
        duration: '12 min',
        theory: `<p><code>let id: string | number;</code> acepta varios tipos.</p>`,
        example: { code: `let valor: string | number;\nvalor = 42;\nvalor = "texto";`, explanation: 'Union con |.' },
        exercise: {
          instructions: 'let estado: "ok" | "error" = "ok"; console.log(estado);',
          starterCode: ``,
          hint: 'let estado: "ok" | "error"',
          solution: `let estado: "ok" | "error" = "ok";\nconsole.log(estado);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== 'ok') throw new Error('Imprime ok');`,
        },
      },
      {
        id: 'ts-l05',
        title: '5. Generics intro',
        duration: '14 min',
        theory: `<p><code>function primero&lt;T&gt;(arr: T[]): T</code> — tipos reutilizables.</p>`,
        example: { code: `function primero<T>(arr: T[]): T {\n  return arr[0];\n}\nconsole.log(primero([1, 2, 3]));`, explanation: 'T es placeholder de tipo.' },
        exercise: {
          instructions: 'Funcion ultimo<T>(arr: T[]): T que retorne arr[arr.length-1]. console.log(ultimo(["a","b"]));',
          starterCode: ``,
          hint: 'return arr[arr.length - 1];',
          solution: `function ultimo<T>(arr: T[]): T {\n  return arr[arr.length - 1];\n}\nconsole.log(ultimo(["a", "b"]));`,
          runner: 'typescript',
          tests: `if (__logs[0] !== 'b') throw new Error('Imprime b');`,
        },
      },
    ],
  },
  {
    id: 'ts-mod-2',
    title: 'TypeScript intermedio',
    description: 'Arrays, tipos avanzados y enums',
    lessons: [
      {
        id: 'ts-l06',
        title: '6. Arrays tipados',
        duration: '12 min',
        theory: `<p><code>let nums: number[] = [1, 2, 3];</code> o <code>Array&lt;string&gt;</code></p>`,
        example: { code: `const frutas: string[] = ["manzana", "pera"];\nconsole.log(frutas[0]);`, explanation: 'Indice empieza en 0.' },
        exercise: {
          instructions: 'const colores: string[] = ["rojo", "azul"]; console.log(colores[1]);',
          starterCode: ``,
          hint: 'colores[1] es azul',
          solution: `const colores: string[] = ["rojo", "azul"];\nconsole.log(colores[1]);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== 'azul') throw new Error('Imprime azul');`,
        },
      },
      {
        id: 'ts-l07',
        title: '7. Tuplas',
        duration: '12 min',
        theory: `<p><code>let punto: [number, number] = [10, 20];</code> — array de longitud fija.</p>`,
        example: { code: `const par: [string, number] = ["edad", 25];\nconsole.log(par[0], par[1]);`, explanation: 'Cada posicion tiene tipo.' },
        exercise: {
          instructions: 'const dato: [string, boolean] = ["activo", true]; console.log(dato[1]);',
          starterCode: ``,
          hint: 'console.log(dato[1]);',
          solution: `const dato: [string, boolean] = ["activo", true];\nconsole.log(dato[1]);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== 'true') throw new Error('Imprime true');`,
        },
      },
      {
        id: 'ts-l08',
        title: '8. Type aliases',
        duration: '12 min',
        theory: `<p><code>type ID = string | number;</code> crea alias reutilizables.</p>`,
        example: { code: `type Punto = { x: number; y: number };\nconst p: Punto = { x: 1, y: 2 };`, explanation: 'Alias para objetos.' },
        exercise: {
          instructions: 'type Usuario = { nombre: string }; const u: Usuario = { nombre: "Ana" }; console.log(u.nombre);',
          starterCode: ``,
          hint: 'type Usuario = { nombre: string };',
          solution: `type Usuario = { nombre: string };\nconst u: Usuario = { nombre: "Ana" };\nconsole.log(u.nombre);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== 'Ana') throw new Error('Imprime Ana');`,
        },
      },
      {
        id: 'ts-l09',
        title: '9. Enums',
        duration: '12 min',
        theory: `<p><code>enum Rol { Admin, User }</code> — conjunto de constantes nombradas.</p>`,
        example: { code: `enum Estado { Ok, Error }\nconst e: Estado = Estado.Ok;\nconsole.log(e);`, explanation: 'Admin=0, User=1 por defecto.' },
        exercise: {
          instructions: 'enum Nivel { Bajo, Medio, Alto }. const n = Nivel.Medio; console.log(n);',
          starterCode: ``,
          hint: 'enum Nivel { Bajo, Medio, Alto }',
          solution: `enum Nivel { Bajo, Medio, Alto }\nconst n = Nivel.Medio;\nconsole.log(n);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== '1') throw new Error('Medio es 1');`,
        },
      },
      {
        id: 'ts-l10',
        title: '10. Optional y readonly',
        duration: '14 min',
        theory: `<p><code>interface Config { debug?: boolean; }</code> — propiedad opcional con <code>?</code>.</p>`,
        example: { code: `interface Item { id: number; tag?: string; }\nconst i: Item = { id: 1 };`, explanation: 'tag es opcional.' },
        exercise: {
          instructions: 'interface Perfil { nombre: string; bio?: string; } const p: Perfil = { nombre: "Luis" }; console.log(p.nombre);',
          starterCode: ``,
          hint: 'bio? es opcional',
          solution: `interface Perfil { nombre: string; bio?: string; }\nconst p: Perfil = { nombre: "Luis" };\nconsole.log(p.nombre);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== 'Luis') throw new Error('Imprime Luis');`,
        },
      },
    ],
  },
  {
    id: 'ts-mod-3',
    title: 'TypeScript avanzado',
    description: 'Generics, utilidades y proyecto',
    lessons: [
      {
        id: 'ts-l11',
        title: '11. Generics en interfaces',
        duration: '14 min',
        theory: `<p><code>interface Caja&lt;T&gt; { valor: T; }</code> — tipos parametrizados.</p>`,
        example: { code: `interface Par<T> { a: T; b: T; }\nconst p: Par<number> = { a: 1, b: 2 };`, explanation: 'T se sustituye al usar.' },
        exercise: {
          instructions: 'interface Envoltorio<T> { data: T; } const e: Envoltorio<string> = { data: "hola" }; console.log(e.data);',
          starterCode: ``,
          hint: 'interface Envoltorio<T> { data: T; }',
          solution: `interface Envoltorio<T> { data: T; }\nconst e: Envoltorio<string> = { data: "hola" };\nconsole.log(e.data);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== 'hola') throw new Error('Imprime hola');`,
        },
      },
      {
        id: 'ts-l12',
        title: '12. keyof y typeof',
        duration: '14 min',
        theory: `<p><code>keyof Obj</code> obtiene claves. <code>typeof x</code> infiere tipo de variable.</p>`,
        example: { code: `const user = { id: 1, name: "Ana" };\ntype UserKeys = keyof typeof user;`, explanation: 'Utilidades de tipos.' },
        exercise: {
          instructions: 'const config = { theme: "dark" }; console.log(config.theme);',
          starterCode: ``,
          hint: 'console.log(config.theme);',
          solution: `const config = { theme: "dark" };\nconsole.log(config.theme);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== 'dark') throw new Error('Imprime dark');`,
        },
      },
      {
        id: 'ts-l13',
        title: '13. Arrow functions tipadas',
        duration: '12 min',
        theory: `<p><code>const suma = (a: number, b: number): number =&gt; a + b;</code></p>`,
        example: { code: `const doble = (n: number): number => n * 2;\nconsole.log(doble(4));`, explanation: 'Sintaxis compacta.' },
        exercise: {
          instructions: 'const triple = (n: number): number => n * 3; console.log(triple(5));',
          starterCode: ``,
          hint: 'const triple = (n: number): number => n * 3;',
          solution: `const triple = (n: number): number => n * 3;\nconsole.log(triple(5));`,
          runner: 'typescript',
          tests: `if (__logs[0] !== '15') throw new Error('triple(5)=15');`,
        },
      },
      {
        id: 'ts-l14',
        title: '14. Map y filter tipados',
        duration: '14 min',
        theory: `<p>Arrays tipados funcionan con metodos ES6: map, filter, reduce.</p>`,
        example: { code: `const nums: number[] = [1, 2, 3];\nconsole.log(nums.map(n => n * 2).join(","));`, explanation: 'map transforma cada elemento.' },
        exercise: {
          instructions: 'const nums: number[] = [2, 4, 6]; console.log(nums.filter(n => n > 3).length);',
          starterCode: ``,
          hint: 'filter(n => n > 3)',
          solution: `const nums: number[] = [2, 4, 6];\nconsole.log(nums.filter(n => n > 3).length);`,
          runner: 'typescript',
          tests: `if (__logs[0] !== '2') throw new Error('Quedan 2 numeros > 3');`,
        },
      },
      {
        id: 'ts-l15',
        title: '15. Proyecto: API tipada',
        duration: '20 min',
        theory: `<p>Combina interfaces, funciones tipadas y arrays para modelar datos de una API.</p>`,
        example: { code: `interface Post { id: number; titulo: string; }\nfunction listar(posts: Post[]): Post[] {\n  return posts.filter(p => p.id > 0);\n}\nconsole.log(listar([{ id: 1, titulo: "Hola" }]).length);`, explanation: 'Patron comun en frontends TS.' },
        exercise: {
          instructions: 'interface Tarea { id: number; hecho: boolean; } function pendientes(t: Tarea[]): number { return t.filter(x => !x.hecho).length; } console.log(pendientes([{id:1,hecho:false},{id:2,hecho:true}]));',
          starterCode: ``,
          hint: 'filter(x => !x.hecho).length',
          solution: `interface Tarea { id: number; hecho: boolean; }\nfunction pendientes(t: Tarea[]): number {\n  return t.filter(x => !x.hecho).length;\n}\nconsole.log(pendientes([{ id: 1, hecho: false }, { id: 2, hecho: true }]));`,
          runner: 'typescript',
          tests: `if (__logs[0] !== '1') throw new Error('1 tarea pendiente');`,
        },
      },
    ],
  },
];
